name: shipoka
description: Shipoka Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  animations: ^2.0.4
  auto_size_text: ^3.0.0
  camera: ^0.10.5+9
  country_picker: ^2.0.23
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  dotted_border: ^2.0.3
  device_preview: ^1.1.0
  expandable: ^5.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_otp_text_field: ^1.1.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  gap: ^3.0.1
  get_it:
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  injectable: ^2.3.2
  intl: any
  package_info_plus: ^5.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  provider:
  smooth_star_rating_null_safety: ^1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Black.ttf
        - asset: assets/font/DMSans-BlackItalic.ttf
        - asset: assets/font/DMSans-Bold.ttf
        - asset: assets/font/DMSans-BoldItalic.ttf
        - asset: assets/font/DMSans-italic.ttf
        - asset: assets/font/DMSans-Light.ttf
        - asset: assets/font/DMSans-LightItalic.ttf
        - asset: assets/font/DMSans-Medium.ttf
        - asset: assets/font/DMSans-MediumItalic.ttf
        - asset: assets/font/DMSans-Regular.ttf
        - asset: assets/font/DMSans-Thin.ttf
        - asset: assets/font/DMSans-ThinItalic.ttf

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/



