name: shipoka
description: Shipoka Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  animations: ^2.0.4
  auto_size_text: ^3.0.0
  camera: ^0.10.5+9
  country_picker: ^2.0.23
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  dotted_border: ^2.0.3
  device_preview: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_otp_text_field: ^1.1.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  gap: ^3.0.1
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  injectable: ^2.3.2
  intl: any
  package_info_plus: ^5.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  smooth_star_rating_null_safety: ^1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/font/Aeonik-Air.otf
        - asset: assets/font/Aeonik-AirItalic.otf
        - asset: assets/font/Aeonik-Black.otf
        - asset: assets/font/Aeonik-BlackItalic.otf
        - asset: assets/font/Aeonik-Bold.otf
        - asset: assets/font/Aeonik-BoldItalic.otf
        - asset: assets/font/Aeonik-Light.otf
        - asset: assets/font/Aeonik-LightItalic.otf
        - asset: assets/font/Aeonik-Medium.otf
        - asset: assets/font/Aeonik-MediumItalic.otf
        - asset: assets/font/Aeonik-Regular.otf
        - asset: assets/font/Aeonik-RegularItalic.otf
        - asset: assets/font/Aeonik-Thin.otf
        - asset: assets/font/Aeonik-ThinItalic.otf

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/



